version: '3.1'

services:
  postgres:
    image: postgres:14
    container_name: conduit_db
    ports:
      - "5437:5437"
    environment:
      POSTGRES_USER: conduit
      POSTGRES_PASSWORD: conduit
      POSTGRES_DB: conduit_db
      PGPORT: 5437
    volumes:
      - conduit_db:/var/lib/postgresql/data

volumes:
  conduit_db: